version: "2.4"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.0.1
    build: filebeat
    container_name: filebeat
    hostname: mydockerhost
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=https://testelk.es.us-central1.gcp.cloud.es.io:9243
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=lZgjAPYnA3PJhz0bKZDY2gkJ
    labels:
      co.elastic.logs/enabled: "false"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    restart: unless-stopped
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
      - "SERVER_NAME=localhost"
      - "XPACK_MONITORING_ENABLED=false"
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
volumes:
  elasticsearch_data:
